name: l9859-env
channels:
  - conda-forge
  - defaults
dependencies:
  - george=0.4.0
  - h5py=3.11.0
  - hdf5=1.12.1
  - libgfortran5=11.3.0
  - numpy=1.24.3
  - pip=24.0
  - python=3.8.18
  - pip:
      - anesthetic==2.8.1
      - astropy==5.2.2
      - getdist==1.4.9
      - matplotlib==3.7.5
      - pandas==2.0.3
      - radvel==1.4.11
      - scipy==1.10.1
      - sphinx==7.1.2
      - sphinx-rtd-theme==2.0.0